### ISSUE TITLE
TODO : Mood update

### ISSUE THREAD

**Issue by gbfree** [unitedelite/tgstation-master#3]
## Sytèmes
- [x]  Très bas niveau de sanité cause un brain trauma (75%mild, 25% severe?).
- [x]  Mood varie selon la beauté de la piece. Effet negatifs augmenté si fussy. Theoriquement semi implémenté mais bug/useless.
Objectif : Pourir **lentement** le mood quand passe un long moment en maitenance/zone couverte de sang/ect. 
- [ ] A améliorer : Prendre en compte le type du sol
- [ ]  Impossible de soigner un brain trauma sans avoir fait remonte+r le niveau de sanité. Attendre retour avant d'implementer (certains des trauma graves sont super handicapants).
- [x]  Augmenter la durée des bonus de mood? A balance.
- [x]  A bas niveau de sanité : faire perdre du mood/reduire les gains de mood hors psy/chimie. TLDR : Quand on fond du trou difficile de remonter sans passer en medbay, quand ça va un cocktail au bar suffit.
- [x] Nerf le quirk qui empèche la sanité de remonter. Probablement passer en reduit la vitesse à laquelle remonte la sanité.
 ## Impact metiers moral
- [x] Psy
 Theoriquement existe deja : le bureau du psy offre un boost de moral, de meme pour pet ses animaux. Maybe ajouter un bonus en présence du psy.  A balance.
- [x] Chimie
La quasi totalité des drogues boost deja le moral.  A balance. Ecrire un guide.
- [x] Clown
 Theoriquement existe deja : la présence du clown et son équipements augmente le mood.  A balance.
- [x] Mime
- [x] Prètre
 Theoriquement existe deja :  le prètre peut monter le moral en bénissant.   A balance.
- [x] Bar
 Existe deja :  les coctail peuvent donner beaucoup de moral (+8). Bonus moral au bar. A balance.
- [x] Cuisine
Existe deja :  la nouriture boost légèrement le moral. Avoir faim pourit le moral. Bonus moral au bar.  A balance.
## Revamp psy
- [ ] Soigner les traumas ?

**Comment by gbfree** [comment]
Voir #7

**Comment by gbfree** [comment]
Idée ajouter des skill ships au professions concernées : 
- Clown : quand il parle boost de moral pour les personnes proches
- Mime  : quand il mime boost de moral pour les personnes proches
- Psy : quand il parle très faible boost de moral pour les personnes proches (ou une reduc des malus de moral ? Serrait plus simple de ne l'appliquer qu'a basse sanité), léger soin des dmgs cerveau, faible chance soigner trauma léger ou de réduire niveau trauma.
- Chapelin : ???????
